name: CI
on: [ push, pull_request ]

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: 2025.1.14
      - name: Remove rust from mise
        run: |
          # a different rust version will be installed in the next step
          mise rm rust
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2.8.0
      - run: lefthook run --force pre-commit
      - run: cargo hack test --feature-powerset
      - uses: wagoid/commitlint-github-action@v6
        with:
          failOnWarnings: true
          failOnErrors: true
